config/routes.rb
Windscreen::Application.routes.draw do
  resources :flashers

  resources :meta

  get 'noctrl' => 'welcome#noctrl', :as => 'noctrl'
  get 'noscreen' => 'welcome#noscreen', :as => 'noscreen'

  get "control/" => 'control#index', :as => :control
  post "control/cue" => 'control#cue', :as => :cue_screen
  post "control/screen" => 'control#screen', :as => :control_screen
  post "control/flasher" => 'control#flasher', :as => :control_flasher
  post "control/refresh" => 'control#refresh', :as => :control_refresh
  post "control/passthrough" => 'control#passthrough', :as => :control_passthrough
  get "display/" => 'display#index', :as => :display

  post "session/create", :as => 'login'
  get "session/destroy", :as => 'logout'

  resources :users
  resources :screens do
    member do
      get 'approve'
      get 'unapprove'
      get 'enable'
      get 'disable'
    end
  end

  root :to => 'welcome#index'

end

app/controllers/control_controller.rb
class ControlController < ApplicationController
  before_filter :check_for_operator, :except => ['passthrough']
  def index
  end

  def nav
    @user = current_user
    @url = params[:url]
    meta('lastURL').set @url
    meta('lastScreen').set 0
  end

  def raw
    @user = current_user
    @data = params[:data].gsub("'", "\\\\'")
    meta('lastURL').set(meta('defaultURL'))
    meta('lastScreen').set 0
  end
  
  def screen
    @user = current_user
    @screen = Screen.where(:name => params[:commit]).first
    meta('lastURL').set @screen.base
    meta('lastScreen').set @screen.id
  end

  def cue
      @user = current_user
      @op = params[:commit]
      if @op != "Move to Screen -->"
          @screen = Screen.where(:name => @op).first
      else
          @screen = Screen.find(meta('lastCue').value)
      end
      meta('cueURL').set(@screen.base + '?cue=1')
      meta('lastCue').set @screen.id
  end

  def refresh
  end

  def flasher
      @flasher = Flasher.find(params[:flasher_id])
  end

  def passthrough
  end
end

app/views/control/cue.js.erb
<% if @op == "Move to Screen -->" %>
 <% 
  m = meta("nowPlaying").set(render :partial => 'control/meta/screen', :locals => {:screen => @screen, :user => @user})
%>
   flash("Playing <%= @screen.name %>", "success");
    <% publish_to "/windscreen/ctrl" do %>
        setContent('<%= @screen.base %>');
    <% end %>

    <% publish_to "/windscreen/meta" do %>
        $("#meta").html('<%= j m.value %>');
        $("#screenControl").attr('src', '<%= @screen.control_url %>');
    <% end %>

<% else %>
    flash("Cue set to <%= @screen.name %>", "success");
    $("#cueControl").attr('src', '<%= @screen.control_url %>?cue=1');
<% end %>

app/views/control/flasher.js.erb
flash("Flashing <%= @flasher.name %>", "success");

<% publish_to "/windscreen/ctrl" do %>
  doFlash('<%= @flasher.graphic.url(:screen) %>');
<% end %>

app/views/control/index.html.erb
<div class="row">
    <%= subscribe_to "/windscreen/meta" %>
    <div id="meta" class="span12">
        <%= meta("nowPlaying").value.html_safe %>
    </div>
</div>
<div class="row">
    <div class="span6">
        <h2>Cueing</h2>
    </div>
    <div class="span6">
        <h2>Live</h2>
    </div>
</div>
<div class="row">
<div class="span6">
    <%= form_tag cue_screen_path, :remote => true do %>
        <div style="margin-bottom: 20px;">
            <% Screen.where(:enabled => true, :approved => true).each do |screen| %>
                <%= submit_tag screen.name, :class => 'btn btn-primary btn-ctrl' %>
            <% end %>
        </div>

        <div id="cueContainer">
            <iframe id="cueControl" class="ctrlFrame" src="<%= meta('lastCue').value == '' ? noctrl_path : Screen.find(meta('lastCue').value).control_url + "?cue=1" %>"></iframe>
        </div>
        <%= submit_tag "Move to Screen -->", :class => 'btn btn-success btn-large' %>
    <% end %>
</div>


<div class="span6">
    <div>
        <%= form_tag control_screen_path, :remote => true do %>
            <% Screen.where(:enabled => true, :approved => true).each do |screen| %>
                <%= submit_tag screen.name, :class => 'btn btn-success btn-ctrl' %>
            <% end %>
        <% end %>
    </div>

    <div id="controlContainer">
        <iframe id="screenControl" class="ctrlFrame" src="<%= meta('lastScreen').value == '' ? noctrl_path : Screen.find(meta('lastScreen').value).control_url %>">
        </iframe>
    </div>

    <%= form_tag control_refresh_path, :remote => true do %>
        <%= submit_tag "Panic Refresh", :class => 'btn btn-large btn-danger' %>
    <% end %>
</div>
</div>

<div class="row">
    <h2>Flash Graphics</h2>

    <% Flasher.all.each do |f| %>
        <%= form_tag control_flasher_path, :remote => true do %>
            <%= hidden_field_tag :flasher_id, f.id %>
            <%= submit_tag f.name, :class => 'btn btn-inverse' %>
        <% end %>
    <% end %>
</div>

app/views/control/nav.js.erb
flash("Navigated to <%= @url %>", "success");
<% 
    m = meta("nowPlaying").set(render :partial => 'control/meta/nav', :locals => {:url => @url, :user => @user})
%>

<% publish_to "/windscreen/ctrl" do %>
    setContent('<%= @url %>');
<% end %>

<% publish_to "/windscreen/meta" do %>
    $("#meta").html('<%= j m.value %>');
    $("#screenControl").attr('src', '<%= noctrl_url %>');
<% end %>

app/views/control/passthrough.js.erb
<% publish_to '/windscreen/ctrl' do %>
    passthroughCommand("<%= params[:cmd] %>");
<% end %>

app/views/control/raw.js.erb
flash("Set content.", "success");

<% 
  m = meta("nowPlaying").set(render :partial => 'control/meta/raw', :locals => {:user => @user})
%>

<% publish_to "/windscreen/ctrl" do %>
  $('#screen').attr('src', "data:text/html;charset=utf-8," + '<%= @data.html_safe %>');
<% end %>

<% publish_to "/windscreen/meta" do %>
  $("#meta").html('<%= j m.value %>');
  $("#screenControl").attr('src', '<%= noctrl_url %>');
<% end %>

app/views/control/refresh.js.erb
flash("Refreshing screen", 'error');

<% publish_to '/windscreen/ctrl' do %>
    panicRefresh();
<% end %>

app/views/control/screen.js.erb
flash("Set screen <%= @screen.name %>", "success");
<% 
  m = meta("nowPlaying").set(render :partial => 'control/meta/screen', :locals => {:screen => @screen, :user => @user})
%>

<% publish_to "/windscreen/ctrl" do %>
  setContent('<%= @screen.base %>');
<% end %>

<% publish_to "/windscreen/meta" do %>
  $("#meta").html('<%= j m.value %>');
  $("#screenControl").attr('src', '<%= @screen.control_url %>');
<% end %>