config/routes.rb
Windscreen::Application.routes.draw do
  resources :flashers

  resources :meta

  get 'noctrl' => 'welcome#noctrl', :as => 'noctrl'
  get 'noscreen' => 'welcome#noscreen', :as => 'noscreen'

  get "control/" => 'control#index', :as => :control
  post "control/cue" => 'control#cue', :as => :cue_screen
  post "control/screen" => 'control#screen', :as => :control_screen
  post "control/flasher" => 'control#flasher', :as => :control_flasher
  post "control/refresh" => 'control#refresh', :as => :control_refresh
  post "control/passthrough" => 'control#passthrough', :as => :control_passthrough
  get "display/" => 'display#index', :as => :display

  post "session/create", :as => 'login'
  get "session/destroy", :as => 'logout'

  resources :users
  resources :screens do
    member do
      get 'approve'
      get 'unapprove'
      get 'enable'
      get 'disable'
    end
  end

  root :to => 'welcome#index'

end

app/models/screen.rb
class Screen < ActiveRecord::Base
  attr_accessible :approved, :base, :enabled, :name, :notes, :user_id
  belongs_to :user

  def control_url
    self.base.last == '/' ? self.base + 'ctrl' : self.base + '/ctrl'
  end

  def base_url
    self.base
  end
end

app/controllers/screens_controller.rb
class ScreensController < ApplicationController
  before_filter :check_for_author, :except => [:index, :approve, :unapprove]
  before_filter :check_for_manager, :only => [:approve, :unapprove]
  # GET /screens
  def index
    @screens = Screen.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /screens/1
  def show
    @screen = Screen.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /screens/new
  def new
    redirect_to root_path, :alert => "You can't do that." unless current_user.author?
    @screen = Screen.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /screens/1/edit
  def edit
    @screen = Screen.find(params[:id])
    if @screen.user == current_user || current_user.manager?
      respond_to do |format|
        format.html
      end
    else
      redirect_to screens_path, :warning => "You don't have permissions to edit someone else's screen."
    end
  end

  # POST /screens
  def create
    @screen = Screen.new(params[:screen])
    @screen.user = current_user

    if current_user.author?
      respond_to do |format|
        if @screen.save
          format.html { redirect_to @screen, notice: 'Screen was successfully created.' }
        else
          format.html { render action: "new" }
        end
      end
    else
      redirect_to screens_path, :warning => "You don't have permissions to edit someone else's screen."
    end

  end

  # PUT /screens/1
  def update
    @screen = Screen.find(params[:id])
    if @screen.user == current_user || current_user.manager?
     respond_to do |format|
       if @screen.update_attributes(params[:screen])
         format.html { redirect_to @screen, notice: 'Screen was successfully updated.' }
       else
         format.html { render action: "edit" }
       end
      end
    else
      redirect_to screens_path, :warning => "You don't have permissions to edit someone else's screen."
    end
  end

  # DELETE /screens/1
  def destroy
    @screen = Screen.find(params[:id])
    @screen.destroy

    respond_to do |format|
      format.html { redirect_to screens_url }
    end
  end

  def approve
    if current_user.manager?
      @screen = Screen.find(params[:id])
      @screen.approved = true
      @screen.save
      redirect_to @screen, :notice => 'Approved screen.'
    else
      redirect_to @screen, :alert => "You aren't allowed to do that."
    end
  end

  def unapprove
    if current_user.manager?
      @screen = Screen.find(params[:id])
      @screen.approved = false
      @screen.save
      redirect_to @screen, :notice => 'Unapproved screen.'
    else
      redirect_to @screen, :alert => "You aren't allowed to do that."
    end
  end

  def enable
    @screen = Screen.find(params[:id])
    if current_user.manager? || @screen.user == current_user
      @screen.enabled = true
      @screen.save
      redirect_to @screen, :notice => 'Enabled screen.'
    else
      redirect_to @screen, :alert => "You aren't allowed to do that."
    end
  end

  def disable
    @screen = Screen.find(params[:id])
    if current_user.manager? || @screen.user == current_user
      @screen.enabled = false
      @screen.save
      redirect_to @screen, :notice => 'Disabled screen.'
    else
      redirect_to @screen, :alert => "You aren't allowed to do that."
    end
  end
end

app/views/screens/_form.html.erb
<%= form_for(@screen) do |f| %>
  <% if @screen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@screen.errors.count, "error") %> prohibited this screen from being saved:</h2>

      <ul>
      <% @screen.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :base %>
    <%= f.text_field :base %>
  </div>
  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes, :size => '20x4' %>
  </div>
  <% if current_user.manager? %>
    <div class="field">
     <%= f.label :approved %>
      <%= f.check_box :approved %>
    </div>
  <% end %>
  <% if current_user.manager? || current_user == @screen.user %>
  <div class="field">
    <%= f.label :enabled %>
    <%= f.check_box :enabled %>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/screens/edit.html.erb
<h1>Editing screen</h1>

<%= render 'form' %>

<%= link_to 'Show', @screen %> |
<%= link_to 'Back', screens_path %>

app/views/screens/index.html.erb
<h1>Screens</h1>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Base</th>
    <th>User</th>
    <th>Approved</th>
    <th>Enabled</th>
    <th></th>
    <th></th>
  </tr>

<% @screens.each do |screen| %>
  <tr>
    <td><%= link_to screen.name, screen %></td>
    <td><%= screen.base %></td>
    <td><%= link_to screen.user.username, screen.user %></td>
    <td><%= truthy_thumb screen.approved %></td>
    <td><%= truthy_thumb screen.enabled %></td>
    <td>
      <%= link_to 'Edit', edit_screen_path(screen), :class => 'btn-info btn-mini' %>
      <%= link_to 'Destroy', screen, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn-danger btn-mini' %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Screen', new_screen_path, :class => 'btn btn-primary' %>

app/views/screens/new.html.erb
<h1>New screen</h1>

<%= render 'form' %>

<%= link_to 'Back', screens_path %>

app/views/screens/show.html.erb
<h1>Screen - <%= @screen.name %></h1>

<iframe src="<%= @screen.base_url %>" id="preview" frameborder="0" seamless="seamless" width="240" height="96">
</iframe>

<h3>by <%= @screen.user.username %></h3>

<p>
<b>Base URL: </b> <span style="font-family: monospace;"><%= link_to @screen.base_url, @screen.base_url %></span>
</p>
<p>
<b>Control URL: </b> <span style="font-family: monospace;"><%= link_to @screen.control_url, @screen.control_url %></span>
</p>

<p>
<% if @screen.approved %>
  <% if current_user.manager? %>
    <%= link_to 'Unapprove', unapprove_screen_path(@screen), :class => 'btn btn-danger' %>
  <% else %>
    Unapproved
  <% end %>
<% else %>
  <% if current_user.manager? %>
    <%= link_to 'Approve', approve_screen_path(@screen), :class => 'btn btn-success' %>
  <% else %>
    Approved
  <% end %>
<% end %>
</p>

<p>
<% if @screen.enabled %>
  <% if current_user.manager? || @screen.user == current_user %>
    <%= link_to 'Disable', disable_screen_path(@screen), :class => 'btn btn-danger' %>
  <% else %>
    Disabled
  <% end %>
<% else %>
  <% if current_user.manager? || @screen.user == current_user %>
    <%= link_to 'Enable', enable_screen_path(@screen), :class => 'btn btn-success' %>
  <% else %>
    Enabled
  <% end %>
<% end %>
</p>

<p>
<%= link_to 'Edit', edit_screen_path(@screen), :class => 'btn btn-warning' %> 
<%= link_to 'Delete', @screen, :method => :delete, :class => 'btn btn-danger', :confirm => 'Are you really sure?' %>
</p>



<%= link_to 'Back to Screen List', screens_path, :class => 'btn btn-info' %>