config/routes.rb
Windscreen::Application.routes.draw do
  resources :flashers

  resources :meta

  get 'noctrl' => 'welcome#noctrl', :as => 'noctrl'
  get 'noscreen' => 'welcome#noscreen', :as => 'noscreen'

  get "control/" => 'control#index', :as => :control
  post "control/cue" => 'control#cue', :as => :cue_screen
  post "control/screen" => 'control#screen', :as => :control_screen
  post "control/flasher" => 'control#flasher', :as => :control_flasher
  post "control/refresh" => 'control#refresh', :as => :control_refresh
  post "control/passthrough" => 'control#passthrough', :as => :control_passthrough
  get "display/" => 'display#index', :as => :display

  post "session/create", :as => 'login'
  get "session/destroy", :as => 'logout'

  resources :users
  resources :screens do
    member do
      get 'approve'
      get 'unapprove'
      get 'enable'
      get 'disable'
    end
  end

  root :to => 'welcome#index'

end

app/models/flasher.rb
class Flasher < ActiveRecord::Base
  attr_accessible :name, :graphic
  has_attached_file :graphic, :styles => {:screen => '240x96'}
end

app/controllers/flashers_controller.rb
class FlashersController < ApplicationController
  before_filter :check_for_manager
  # GET /flashers
  # GET /flashers.json
  def index
    @flashers = Flasher.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @flashers }
    end
  end

  # GET /flashers/1
  # GET /flashers/1.json
  def show
    @flasher = Flasher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @flasher }
    end
  end

  # GET /flashers/new
  # GET /flashers/new.json
  def new
    @flasher = Flasher.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @flasher }
    end
  end

  # GET /flashers/1/edit
  def edit
    @flasher = Flasher.find(params[:id])
  end

  # POST /flashers
  # POST /flashers.json
  def create
    @flasher = Flasher.new(params[:flasher])

    respond_to do |format|
      if @flasher.save
        format.html { redirect_to @flasher, notice: 'Flasher was successfully created.' }
        format.json { render json: @flasher, status: :created, location: @flasher }
      else
        format.html { render action: "new" }
        format.json { render json: @flasher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /flashers/1
  # PUT /flashers/1.json
  def update
    @flasher = Flasher.find(params[:id])

    respond_to do |format|
      if @flasher.update_attributes(params[:flasher])
        format.html { redirect_to @flasher, notice: 'Flasher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @flasher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flashers/1
  # DELETE /flashers/1.json
  def destroy
    @flasher = Flasher.find(params[:id])
    @flasher.destroy

    respond_to do |format|
      format.html { redirect_to flashers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/flashers_helper.rb
module FlashersHelper
end

app/views/flashers/_form.html.erb
<%= form_for(@flasher) do |f| %>
  <% if @flasher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flasher.errors.count, "error") %> prohibited this flasher from being saved:</h2>

      <ul>
      <% @flasher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :graphic %><br />
    <%= f.file_field :graphic %>
  </div>
  <div class="actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/flashers/edit.html.erb
<h1>Editing flasher</h1>

<%= render 'form' %>

<%= link_to 'Show', @flasher %> |
<%= link_to 'Back', flashers_path %>

app/views/flashers/index.html.erb
<h1>Flash Graphics</h1>

<table class="table">
    <% @flashers.in_groups_of(4) do |g| %>
        <tr>
            <% g.each do |f| %>
                <% if f %>
                    <td width="25%">
                        <%= link_to f do %>
                            <%= image_tag f.graphic.url(:screen) %><br/>
                            <%= f.name %>
                        <% end %>
                    </td>
                <% end %>
            <% end %>
        </tr>
    <% end %>
</table>

<br />

<%= link_to 'New Flasher', new_flasher_path %>

app/views/flashers/new.html.erb
<h1>New flasher</h1>

<%= render 'form' %>

<%= link_to 'Back', flashers_path %>

app/views/flashers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @flasher.name %>
</p>

<p>
  <b>Graphic:</b>
  <%= image_tag @flasher.graphic.url(:screen) %>
</p>

<%= link_to 'Edit', edit_flasher_path(@flasher) %> |
<%= link_to 'Back', flashers_path %>