config/routes.rb
Windscreen::Application.routes.draw do
  resources :flashers

  resources :meta

  get 'noctrl' => 'welcome#noctrl', :as => 'noctrl'
  get 'noscreen' => 'welcome#noscreen', :as => 'noscreen'

  get "control/" => 'control#index', :as => :control
  post "control/cue" => 'control#cue', :as => :cue_screen
  post "control/screen" => 'control#screen', :as => :control_screen
  post "control/flasher" => 'control#flasher', :as => :control_flasher
  post "control/refresh" => 'control#refresh', :as => :control_refresh
  post "control/passthrough" => 'control#passthrough', :as => :control_passthrough
  get "display/" => 'display#index', :as => :display

  post "session/create", :as => 'login'
  get "session/destroy", :as => 'logout'

  resources :users
  resources :screens do
    member do
      get 'approve'
      get 'unapprove'
      get 'enable'
      get 'disable'
    end
  end

  root :to => 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><%= content_for?(:title) ? yield(:title) : "WindScreen" %></title>
        <%= csrf_meta_tags %>

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
        <![endif]-->

        <%= stylesheet_link_tag "application", :media => "all" %>
        <%= javascript_include_tag "application" %>
    </head>
    <body>

        <div class="navbar navbar-fluid-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <% if current_user %>
                        <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </a>
                    <% end %>

                    <a class="brand" href="#">WindScreen</a>
                    <% if current_user %>
                        <div class="container-fluid nav-collapse">
                            <ul class="nav">
                                <li><%= link_to "Log Out", logout_path %></li>
                                <% if current_user && current_user.author? %><li><%= link_to "Screens", screens_path  %></li><% end %>
                                <% if current_user && current_user.manager? %><li><%= link_to "Flash Graphics", flashers_path  %></li><% end %>
                                <% if current_user && current_user.admin? %><li><%= link_to "Users", users_path  %></li><% end %>
                                <% if current_user && current_user.operator? %><li><%= link_to "Control", control_path  %></li><% end %>
                                <% if current_user %><li><%= link_to "Display", display_path  %></li><% end %>
                            </ul>
                        <% end %>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>



        <div class="container" style="text-align: center;">
            <div class="row">
                <div class="span12">
                    <div id="flashBox">
                        <%= bootstrap_flash %>
                    </div>

                    <%= yield %>
                </div>
            </div><!--/row-->
        </div> <!-- /container -->

        <!-- Javascripts
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script>
            $(document).ready(function(){
                setTimeout(function(){
                    $('#flashbox  .alert').hide('fast', function(){ $target.remove(); });
                }, 5000);
            })

        </script>
    </body>
</html>

app/views/layouts/display.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Windscreen" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "display" %>
    <%= javascript_include_tag "display" %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>